spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:/Users/tomas/IdeaProjects/todo-app/todo-app/todo-db'
  jpa:
    hibernate:
      ddl-auto: validate
